// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CharacterImage: typeof import('./src/components/Character/CharacterImage.vue')['default']
    Footer: typeof import('./src/components/Layout/Footer.vue')['default']
    GridCharacterCard: typeof import('./src/components/Grid/Character/GridCharacterCard.vue')['default']
    GridCharacterList: typeof import('./src/components/Grid/Character/GridCharacterList.vue')['default']
    GridFilterSearch: typeof import('./src/components/Grid/Filter/GridFilterSearch.vue')['default']
    GridFilterStatus: typeof import('./src/components/Grid/Filter/GridFilterStatus.vue')['default']
    GridNavigation: typeof import('./src/components/Grid/GridNavigation.vue')['default']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    Hero: typeof import('./src/components/Layout/Hero.vue')['default']
    IconCarbonMoon: typeof import('~icons/carbon/moon')['default']
    IconCarbonSun: typeof import('~icons/carbon/sun')['default']
    IconCifBr: typeof import('~icons/cif/br')['default']
    IconCifGb: typeof import('~icons/cif/gb')['default']
    IconMdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    IconMdiBroom: typeof import('~icons/mdi/broom')['default']
    IconMdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    IconMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IconMdiCircle: typeof import('~icons/mdi/circle')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiEraser: typeof import('~icons/mdi/eraser')['default']
    IconMdiSearch: typeof import('~icons/mdi/search')['default']
    Logo: typeof import('./src/components/Layout/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
